# Using GoControl CECOMINOD016164 HUSBZB-1 USB Hub
# Zwave - /dev/ttyUSB0
# Zigbee - /dev/ttyUSB1

usb_path: /dev/ttyUSB0
network_key: "0xF5, 0x21, 0x10, 0xF5, 0x1E, 0x1D, 0x3D, 0xCB, 0x37, 0x44, 0xFD, 0x5E, 0x89, 0x49, 0xF0, 0xB5"
polling_interval: 10000
config_path: /config/OZW/config
device_config_glob: 
  fan.*:
    ignored: false
    polling_intensity: 1
  light.*:
    ignored: false
    polling_intensity: 1
    refresh_value: true
    delay: 2
  switch.*:
    ignored: false
    polling_intensity: 1
  # Making these show up as lights in light: section
  switch.jasco_products_12722_on_off_relay_switch_*:
    ignored: false
    polling_intensity: 1
    refresh_value: true
    delay: 2