language: python

python: "3.6.4"

before_install:
  - mv travis_secrets.yaml secrets.yaml
  - sudo apt-get install -y libudev-dev python-dev pkg-config libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libswresample-dev libavfilter-dev

install:
  - pip3 install homeassistant
  - pip3 install colorlog

script:
  - hass -c . --script check_config --info all