# Single Files
automation: !include automations.yaml

# Radios
zwave: !include_dir_merge_named zwave/
zha: !include_dir_merge_named zigbee/

# Cloud Services
# <Broken For now: https://community.home-assistant.io/t/sense-energy-monitor-enhanced-to-include-devices/57572/48> sense: !include_dir_merge_named sense/

# Directories
homeassistant: !include_dir_merge_named homeassistant/
tts: !include_dir_merge_list tts/
group: !include_dir_merge_named group/
script: !include_dir_merge_named script/
sensor: !include_dir_merge_list sensor/
logger: !include_dir_merge_named logger/