# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Single Files
automation: !include automations.yaml

# Cloud Services
sense: !include_dir_merge_named sense/

# Logging
# logger: !include_dir_merge_named logger/
# recorder: !include_dir_merge_named recorder/
# history: !include_dir_merge_named history/

# Notifications
notify: !include_dir_merge_list notify/
telegram_bot: !include_dir_merge_list telegram_bot/

# Directories
homeassistant: !include_dir_merge_named homeassistant/
tts: !include_dir_merge_list tts/
group: !include_dir_merge_named group/
script: !include_dir_merge_named script/
sensor: !include_dir_merge_list sensor/
# camera: !include_dir_merge_list camera/
discovery: !include_dir_merge_named discovery/
device_tracker: !include_dir_merge_list device_tracker/
zone: !include_dir_merge_list zone/
media_player: !include_dir_merge_list media_player/
# influxdb: !include_dir_merge_named influxdb/
panel_iframe: !include_dir_merge_named panel_iframe/
light: !include_dir_merge_list light/
weather: !include_dir_merge_list weather/