switch.jasco_products_12722_on_off_relay_switch_switch
- platform: switch
  name: Hallway
  entity_id: switch.jasco_products_12722_on_off_relay_switch_switch
- platform: switch
  name: Guest Bathroom
  entity_id: switch.jasco_products_12722_on_off_relay_switch_switch_2
- platform: switch
  name: Master Bathroom Left
  entity_id: switch.jasco_products_12722_on_off_relay_switch_switch_3
- platform: switch
  name: Master Bathroom Right
  entity_id: switch.jasco_products_12722_on_off_relay_switch_switch_4
- platform: switch
  name: Space Basement Switch (Left)
  entity_id: switch.jasco_products_12722_on_off_relay_switch_switch_5