- name: Daycare
  latitude: !secret daycare_lat
  longitude: !secret daycare_long
  radius: !secret daycare_radius
  icon: mdi:baby-buggy
  passive: false

- name: Sikorsky
  latitude: !secret sikorsky_lat
  longitude: !secret sikorsky_long
  radius: !secret sikorsky_radius
  icon: mdi:cash-marker
  passive: false

- name: Keene
  latitude: !secret keene_lat
  longitude: !secret keene_long
  radius: !secret keene_radius
  icon: mdi:cash-marker
  passive: false

- name: Wilmington
  latitude: !secret wilmington_lat
  longitude: !secret wilmington_long
  radius: !secret wilmington_radius
  icon: mdi:cash-marker
  passive: false