- name: Daycare
  latitude: !secret daycare_lat
  longitude: !secret daycare_long
  radius: !secret daycare_radius
  icon: mdi:baby-buggy
  passive: false

- name: Sikorsky
  latitude: !secret sikorsky_lat
  longitude: !secret sikorsky_long
  radius: !secret sikorsky_radius
  icon: mdi:cash-marker
  passive: false

- name: Pitney Bowes
  latitude: !secret pb_lat
  longitude: !secret pb_long
  radius: !secret pb_radius
  icon: mdi:cash-marker
  passive: true