- platform: generic
  name: Driveway
  still_image_url: !secret camera_driveway_image_url
  stream_source: !secret camera_driveway_stream_source 
  verify_ssl: false
- platform: generic
  name: Alice Camera
  still_image_url: !secret camera_alice_image_url
  stream_source: !secret camera_alice_stream_source