- platform: rest
  name: Statewide Covid Stats
  resource: https://covidtracking.com/api/states?state=ct
  json_attributes:
    - date
    - state
    - positive
    - negative
    - pending
    - hospitalizedCurrently
    - hospitalizedCumulative
    - inIcuCurrently
    - inIcuCumulative
    - onVentilatorCurrently
    - onVentilatorCumulative
    - recovered
    - dataQualityGrade
    - lastUpdateEt
    - dateModified
    - checkTimeEt
    - death
    - hospitalized
    - dateChecked
    - totalTestsViral
    - positiveTestsViral
    - negativeTestsViral
    - positiveCasesViral
    - deathConfirmed
    - deathProbable
    - fips
    - positiveIncrease
    - negativeIncrease
    - total
    - totalTestResults
    - totalTestResultsIncrease
    - posNeg
    - deathIncrease
    - hospitalizedIncrease
    - hash
    - commercialScore
    - negativeRegularScore
    - negativeScore
    - positiveScore
    - score
    - grade
  value_template: '{{ value_json.state }}'
  scan_interval: 3600
- platform: template
  sensors:
    covid_postive_state:
      friendly_name: 'positive covid state'
      value_template: '{{ states.sensor.statewide_covid_stats.attributes["positive"] }}'
    covid_negative_state:
      friendly_name: 'negative Covid State'
      value_template: '{{ states.sensor.statewide_covid_stats.attributes["negative"] }}'
    covid_pending_state:
      friendly_name: 'pending Covid State'
      value_template: '{{ states.sensor.statewide_covid_stats.attributes["pending"] }}'
    covid_hospitalized_state:
      friendly_name: 'hospitalized Covid State'
      value_template: '{{ states.sensor.statewide_covid_stats.attributes["hospitalized"] }}'
    covid_death_state:
      friendly_name: 'death Covid State'
      value_template: '{{ states.sensor.statewide_covid_stats.attributes["death"] }}'
    covid_total_state:
      friendly_name: 'total Covid State'
      value_template: '{{ states.sensor.statewide_covid_stats.attributes["total"] }}'
    covid_update_state:
      friendly_name: 'last update Covid State'
      value_template: '{{ states.sensor.statewide_covid_stats.attributes["lastUpdateEt"] }}'
    covid_hospitalizedCurrently_state:
      friendly_name: 'last hospitalizedCurrently Covid State'
      value_template: '{{ states.sensor.statewide_covid_stats.attributes["hospitalizedCurrently"] }}'
    covid_deathIncrease_state:
      friendly_name: 'last deathIncrease Covid State'
      value_template: '{{ states.sensor.statewide_covid_stats.attributes["deathIncrease"] }}'
    covid_hospitalizedIncrease_state:
      friendly_name: 'last hospitalizedIncrease Covid State'
      value_template: '{{ states.sensor.statewide_covid_stats.attributes["hospitalizedIncrease"] }}'